//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CloudTransformerTemplate.Core.DocumentTypes
{
	// Mixin Content Type with alias "compositionSitemapPage"
	/// <summary>Composition Sitemap Page</summary>
	public partial interface ICompositionSitemapPage : IPublishedContent
	{
		/// <summary>Sitemap Change Frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string SitemapChangeFrequency { get; }

		/// <summary>Sitemap Priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		decimal SitemapPriority { get; }
	}

	/// <summary>Composition Sitemap Page</summary>
	[PublishedModel("compositionSitemapPage")]
	public partial class CompositionSitemapPage : PublishedContentModel, ICompositionSitemapPage
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "compositionSitemapPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CompositionSitemapPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CompositionSitemapPage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Sitemap Change Frequency: Suggestion to search engines with regards to how often the content of the page will.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sitemapChangeFrequency")]
		public string SitemapChangeFrequency => GetSitemapChangeFrequency(this);

		/// <summary>Static getter for Sitemap Change Frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetSitemapChangeFrequency(ICompositionSitemapPage that) => that.Value<string>("sitemapChangeFrequency");

		///<summary>
		/// Sitemap Priority: The priority of this page relative to other pages on your.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sitemapPriority")]
		public decimal SitemapPriority => GetSitemapPriority(this);

		/// <summary>Static getter for Sitemap Priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static decimal GetSitemapPriority(ICompositionSitemapPage that) => that.Value<decimal>("sitemapPriority");
	}
}
